### Login again
POST http://localhost:8082/mangaSt/auth/authenticate
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123"
}

> {% client.global.set("new-auth-token", response.body.access_token); %}

### Create the new book
POST http://localhost:8082/mangaSt/admin/production/addProd
Content-Type: application/json
Authorization: Bearer {{new-auth-token}}

{
  "title": "War and peace",
  "author": "Lev Tolstoy",
  "typeBook": "Book",
  "categories": ["Crime","Drama","Romance"]
}